import Contacts from "./components/Contacts";
import { AuthProvider } from "./context/AuthContext";
import "./globals.css";
import { config } from '@fortawesome/fontawesome-svg-core';
import '@fortawesome/fontawesome-svg-core/styles.css'; // Import the CSS
config.autoAddCss = false; // Prevents Font Awesome from adding its own CSS

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="scrollbar scrollbar-thumb-gray-500 scrollbar-track-black-900 overflow-y-scroll">
        <AuthProvider>
          {children}
        </AuthProvider>
        <footer className="p-0">
          <Contacts />
        </footer>
      </body>
    </html>
  );
}

































// import type { Metadata } from "next";
// import Contacts from "./components/Contacts";
// import {AuthProvider} from "./context/AuthContext"
// import "./globals.css";
// import { config } from '@fortawesome/fontawesome-svg-core'
// import '@fortawesome/fontawesome-svg-core/styles.css' // Import the CSS
// config.autoAddCss = false; // Prevents Font Awesome from adding its own CSS

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className="scrollbar scrollbar-thumb-gray-500 scrollbar-track-black-900 overflow-y-scroll">
//       <AuthProvider>
//         {children}
//         </AuthProvider>
//         <footer className="p-0">
//           <Contacts />
//         </footer>
//       </body>
//     </html>
//   );
// }
